import type { Metadata } from "next";
import "./globals.css";
import { inter, readexPro } from "@/fonts";
import { cn } from "@/lib/utils";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          readexPro.className,
          "bg-black text-white overflow-x-hidden"
        )}
      >
        {children}
      </body>
    </html>
  );
}
